spring:
    servlet:
        multipart:
            #최대 업로드 파일의 크기 설정
            max-file-size: 1073741824
            #요청당(사용자가) 업로드할 수 있는 파일의 최대 크기 설정
            max-request-size: 1048576
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:XE
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: SPRING_BOOT1
        password: 1234
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
            
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:com/ktdsuniversity/edu/**/dao/mapper/*.xml
    
    #파일업로드 커스텀
app:
    multipart: # 파일업로드 정책 관련 설정.
        # 업로드한 파일이 저장될 위치
        base-dir: C:/uploadFiles
        obfuscation: #파일명 난독화 관련 설정
                #난독화 사용여부 
                enable: true
                hide-ext: # 파일명에서 확장자 숨길것인지에 대한 설정
                    enable: true
                    
